version: '3'
services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb
    
    
  postgresdb:
    image: postgres
    ports:
    - "5555:5432"
    environment:
    - POSTGRES_USER=pipelinetwitter_ps
    - POSTGRES_PASSWORD=12345
    - POSTGRES_DB=pipelinetwitter_ps
    
    # to enter the docker-compose psql use the following comand:    
   # psql -U pipelinetwitter_ps -h 0.0.0.0 -p 5555 pipelinetwitter_ps

    

  etl_job:
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on:
    - mongodb
    - postgresdb
    
    


